Repository atlp-rwanda/cabal-phantom-backend, pull requests merged in 2020-10, with the labels that each got.

#9 #usCaESGS-App-Internationalization
  .gitignore
  package-lock.json
  package.json
  src/contollers/welcome.js
  src/languages/international.js
  src/languages/locales/en.json
  src/languages/locales/fr.json
  src/languages/locales/ki.json
  src/routes/routeWelcome.js
Labels: Members review needed, TTL review

#7 #S7fu8nT3 Setup continuous integration and Heroku pipeline
  .coveralls.yml
  .gitignore
  .travis.yml
  Procfile
  README.md
  package-lock.json
  package.json
  src/database/config/config.js
  src/database/migrations/20200923091053-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20200925164209-User.js
  src/server.js
  src/test/test.js
Labels: TTL review

#12 #qSwfwWJp-Sign-In-to-Phantom
  .DS_Store
  .env.example
  .sequelizerc
  .travis.yml
  locales/en.json
  locales/fr.json
  locales/rw.json
  package-lock.json
  package.json
  src/app.js
  src/contollers/userSignIn.js
  src/database/seeders/20200925164209-User.js
  src/routes/userRouters.js
  src/test/test.js
  src/utils/jwt.js
  swagger.json
Labels: TTL review

#15 #zqZkd9M8 Roles and Permissions
  .coveralls.yml
  .gitignore
  .sequelizerc
  .travis.yml
  locales/en.json
  locales/fr.json
  locales/rw.json
  package-lock.json
  package.json
  src/app.js
  src/contollers/userSignIn.js
  src/controller/userControllers.js
  src/database/seeders/20200925164209-User.js
  src/language/languageConfig.js
  src/language/locales/en.json
  src/language/locales/fr.json
  src/language/locales/rw.json
  src/middleware/checkEmailExist.js
  src/middleware/protectRoutes.js
  src/routes/index.js
  src/routes/userRouters.js
  src/server.js
  src/test/mock/userMocks.js
  src/test/test.js
  src/test/testAuth.js
  src/test/testUser.js
  src/utils/jwt.js
  src/validation/roleValidation.js
  swagger.json
Labels: TTL review

#17 #9JpkBREJ ft-register-drivers-and-operators-with proper validations
  .DS_Store
  package-lock.json
  package.json
  src/controller/userControllers.js
  src/language/locales/en.json
  src/language/locales/fr.json
  src/language/locales/rw.json
  src/routes/userRouters.js
  src/test/mock/registerMocks.js
  src/test/test.js
  src/test/testRegister.js
  src/utils/email.js
  src/utils/generateDefaultRole.js
  src/utils/generatePassword.js
  src/validation/userValidation.js
  swagger.json
Labels: Members review needed
